from .st_gcn_aaai18 import ST_GCN_18
from .st_gcn_aaai18_ordinal import ST_GCN_18_ordinal
from .st_gcn_aaai18_ordinal_smaller_1 import ST_GCN_18_ordinal_smaller_1
from .st_gcn_aaai18_ordinal_smaller_2 import ST_GCN_18_ordinal_smaller_2
from .st_gcn_aaai18_ordinal_smaller_3 import ST_GCN_18_ordinal_smaller_3
from .st_gcn_aaai18_ordinal_smaller_4 import ST_GCN_18_ordinal_smaller_4
from .st_gcn_aaai18_ordinal_smaller_5 import ST_GCN_18_ordinal_smaller_5
from .st_gcn_aaai18_ordinal_smaller_6 import ST_GCN_18_ordinal_smaller_6
from .st_gcn_aaai18_ordinal_smaller_7 import ST_GCN_18_ordinal_smaller_7
from .st_gcn_aaai18_ordinal_smaller_8 import ST_GCN_18_ordinal_smaller_8
from .st_gcn_aaai18_ordinal_smaller_9 import ST_GCN_18_ordinal_smaller_9
from .st_gcn_aaai18_ordinal_smaller_10 import ST_GCN_18_ordinal_smaller_10

# Supervised contrastive models
from .ST_GCN_18_ordinal_smaller_2_supcon import ST_GCN_18_ordinal_smaller_2_supcon
from .hrnet import HRNet