wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.36
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.7
batch_size:
  desc: null
  value: 100
dataset_cfg_data_source_cache:
  desc: null
  value: true
dataset_cfg_data_source_csv_loader:
  desc: null
  value: true
dataset_cfg_data_source_data_dir:
  desc: null
  value: /home/saboa/data/skel_data/stgcn_normalized_100_center_all_no_norm_plus_belmont
dataset_cfg_data_source_flip_skels:
  desc: null
  value: true
dataset_cfg_data_source_missing_joint_val:
  desc: null
  value: mean
dataset_cfg_data_source_num_keypoints:
  desc: null
  value: 13
dataset_cfg_data_source_num_track:
  desc: null
  value: 1
dataset_cfg_data_source_outcome_label:
  desc: null
  value: SAS_gait
dataset_cfg_data_source_repeat:
  desc: null
  value: 1
dataset_cfg_data_source_type:
  desc: null
  value: datasets.SkeletonLoaderTRI
dir:
  desc: null
  value: /home/saboa/code/mmskeleton/wandb_dryrun/1it0bko6
early_stopping:
  desc: null
  value: true
es_patience_1:
  desc: null
  value: 25
es_start_up_1:
  desc: null
  value: 10
force_run_all_epochs:
  desc: null
  value: false
keypoint_layout:
  desc: null
  value: coco_simplified_head_ankles_ankle_wrists
loss_cfg_type:
  desc: null
  value: mmskeleton.processor.utils_recognition.WingLoss
model_cfg_dropout:
  desc: null
  value: 0.0
model_cfg_edge_importance_weighting:
  desc: null
  value: true
model_cfg_graph_cfg_layout:
  desc: null
  value: coco_simplified_head_ankles_ankle_wrists
model_cfg_graph_cfg_strategy:
  desc: null
  value: spatial
model_cfg_in_channels:
  desc: null
  value: 2
model_cfg_num_class:
  desc: null
  value: 4
model_cfg_num_joints_predicting:
  desc: null
  value: 4
model_cfg_num_ts_predicting:
  desc: null
  value: 1
model_cfg_temporal_kernel_size:
  desc: null
  value: 5
model_cfg_type:
  desc: null
  value: models.backbones.ST_GCN_18_ordinal_orig_position_pretrain_dynamic_v1
model_increase_iters:
  desc: null
  value:
  - 1
  - 2
  - 4
  - 6
  - 8
model_increase_mults:
  desc: null
  value:
  - 1
  - 1
  - 2
  - 1
  - 1
notes:
  desc: null
  value: two_part_loss
num_class:
  desc: null
  value: 4
num_ts_predicting:
  desc: null
  value: 1
optimizer_cfg_lr:
  desc: null
  value: 0.0001
optimizer_cfg_momentum:
  desc: null
  value: 0.9
optimizer_cfg_nesterov:
  desc: null
  value: true
optimizer_cfg_type:
  desc: null
  value: torch.optim.SGD
optimizer_cfg_weight_decay:
  desc: null
  value: 0
outcome_label:
  desc: null
  value: SAS_gait
self_train_iteration_count:
  desc: null
  value: 1
test_AMBID:
  desc: null
  value: 32
test_AMBID_num:
  desc: null
  value: 11
total_epochs:
  desc: null
  value: 200
train_extrema_for_epochs:
  desc: null
  value: 25
wandb_group:
  desc: null
  value: 2x8w946m_SAS_gait_dynamic_v1_pretrain15_dropout0.0_tempkernel5_batch100
wandb_project:
  desc: null
  value: testing_stop2
weight_classes:
  desc: null
  value: true
